### ISSUE TITLE
Pre-compilation

### ISSUE THREAD

**Issue by zdenektopic** [gk-brown/MarkupKit#1]
Hi, this looks amazing. However I dont like the idea of parsing XML again, again and again. I recommend writing some pre-compile script that runs at run-time and then calling `LMViewBuilder.viewWithName()` just executes some code, meaning the XML files wouldnt be even required to be packed with the application.

But it looks amazing, I was wondering when someone rolls out something like this. Great job!

**Comment by gk-brown** [comment]
Thanks for the feedback! Intuitively, I agree that parsing XML repeatedly seems like a bad idea. However, in practice, I have not observed any noticeable penalty. `NSXMLParser` is pretty fast. Also, for views managed by a controller, you're probably only going to process the XML once in `loadView`. For table view cells, you will load it a few more times, but not that many since cells get re-used.

In any case, if you do discover that loading XML is too time-consuming, you could try writing the deserialized view hierarchy out using `encodeWithCoder:`. In other words, you could load it once with `LMViewBuilder` and then write it out using `encodeWithCoder:`. For successive loads, you could reload it from the encoded stream using `initWithCoder:`. I haven't tried this myself, but it should work in theory. I'd be interested to know how it turns out.
