### ISSUE TITLE
support multiple xml designs for different devices

### ISSUE THREAD

**Issue by Frequence-xx** [gk-brown/MarkupKit#21]
an idea is to suffix each files like this: 
LoginView_320X568.xml 
LoginView_375X667.xml 
and let MarkupKit detect the correct xml for each device.
“Lets keep it at points level” we should not bother ourselves the device version or the iOS versions.

**Comment by ravigill** [comment]
+ 1 on this feature.

Building for different screen sizes is a real pain. with this feature one can quickly provide support for different devices including old and future once and re release.

**Comment by gk-brown** [comment]
Yes, I like the idea a lot. In fact, I had considered doing it a while ago and forgot about it until now.  :-)

**Comment by gk-brown** [comment]
I've been giving this some thought, and I think it would probably make sense to base a feature like this on size classes rather than on explicit display sizes:

1) There are already several different device sizes, and more are likely to be added in the future. It would be inconvenient to have to create one layout file for each physical device.

2) This approach doesn't take device orientation into account.

3) This approach assumes that a view will occupy the entire extent of the screen, which is not always the case.

Using size classes would keep the number of layout documents to a minimum, since there are only two options: regular and compact. This would result in a maximum of 4 layout files:

regular width, regular height
regular width, compact height
compact width, regular height
compact width, compact height

It would also work with embedded controllers (i.e. controllers whose views do not occupy the entire screen).

However, I'm not sure what would be the best way to encode this in a file name. Ideally, it would be concise but still easily understandable.

**Comment by gk-brown** [comment]
The following terms could be used to encode the various size class combinations:

* regular width, regular height - "normal"
* regular width, compact height - "horizontal"
* compact width, regular height - "vertical"
* compact width, compact height - "minimal"

For example:

_LoginView~horizontal.xml_

`LMViewBuilder` would first look for a file corresponding to the controller's current size class, and if not found, would fall back to the default (e.g. _LoginView.xml_).

**Comment by gk-brown** [comment]
This is implemented but not yet fully tested or documented.

**Comment by gk-brown** [comment]
This is now tested and documented.

**Comment by ravigill** [comment]
Hi Greg! 

Thanks for this! it looks awsome. We will be implementing this sometime end of the month.

Cheers

**Comment by gk-brown** [comment]
Glad to hear it. There's an example in the wiki, in case you haven't seen it.
