### ISSUE TITLE
Setting weight to nan doesn't work

### ISSUE THREAD

**Issue by sp-wisebits** [gk-brown/MarkupKit#56]
`<LMSpacer height="10" weight="nan"/>`
this causes runtime error because the weight value gets parsed as 0.

btw, is there any way to have LMSpacer with fixed size? Or make a fixed space between 2 adjacent views in a LMColumnView.

**Comment by gk-brown** [comment]
Nice find. Apparently `NSString`'s `floatValue:` method doesn't support `NaN`.

I can think of a couple ways this might be resolved:

* Add support for `NaN` via `applyMarkupPropertyValue:forKey:`. This would work, but it doesn't seem like the right solution. Setting values to `NaN`, either in markup or in code, is not common. So adding special code to handle this case is probably not a good idea.
* Prioritize `height` and `width` over `weight`. This way, your example would work as expected without the need to explicitly clear the `weight` value:
        <LMSpacer height="10"/>

I'll prototype the second option and see how it goes. In the meantime, here are a couple of workarounds:

* Use an empty `UIView` instead of an `LMSpacer`:
        <UIView height="10"/>
* Use nested `LMColumnView`s. For example:
        <LMColumnView>
            
            <LMColumnView spacing="10">
                <UILabel text="Hello"/>
                <UILabel text="World"/>
            </LMColumnView>
            ...
        </LMColumnView>

**Comment by gk-brown** [comment]
I just prototyped this and it works as expected.

**Comment by gk-brown** [comment]
This is resolved. Width and height constraints now take priority over weight constraints. If either `width` or `height` is specified, `weight` is ignored.
