### ISSUE TITLE
Code completion / highlighting

### ISSUE THREAD

**Issue by aceontech** [gk-brown/MarkupKit#65]
This is such an interesting project! I was wondering whether you've thought about how code completion might work. Possibly a custom highlighter for Atom or Visual Studio Code..? Not exactly my area of expertise but I'm intrigued.

**Comment by gk-brown** [comment]
I've definitely thought about it, but I'm not sure what the best way is to approach it. A DTD/schema would seem to make sense, but:

* Although other IDEs such as Eclipse support auto-completion using a DTD or schema, Xcode doesn't
* The set of valid elements and attributes is huge, and effectively unlimited, since you can also create instances of custom types in markup

I think the only way to realistically implement it would be as an Xcode extension, since it would probably need to involve reflection on the actual types and properties available at runtime. Unfortunately, I have no idea where to even begin with that.  :-)

On the other hand, Xcode's XML editor is pretty helpful. Once you've used an element or attribute name at least once, it will automatically suggest it if you start typing something similar.

**Comment by aceontech** [comment]
Not well versed in Xcode extensions either, but I do know there are projects out there (like Swift linters) that use SourceKit. Not sure you get direct access to SourceKit from an Xcode source editor extensions though.. Anyway. Gonna play around with your library a bit first, but based on your documentation, it kind of looks too good to be true/real ;-). 

Is this being used in production somewhere that you know of?

**Comment by gk-brown** [comment]
I use it in a couple of my own apps, and I'm aware of at least one other one. According to CocoaPods, it's being used in 25 (but I can't tell what they are).

I'd love to know more about how people are using it, but one thing GitHub doesn't currently offer is a discussion forum. I've been thinking about setting up something on Gitter (https://gitter.im) but I haven't had a chance to look into it yet. If you have any other suggestions, please let me know!

**Comment by aceontech** [comment]
Cool. Yeah, Gitter, Slack or plain old IRC would be good way to get some discussion going.
Sign me up ;-)

**Comment by gk-brown** [comment]
Just created a Gitter channel for MarkupKit:

https://gitter.im/MarkupKit/Lobby

**Comment by aceontech** [comment]
This can be closed for now. I might still look into the code highlighting/completion issue :).

**Comment by gk-brown** [comment]
OK, great. Definitely feel free to re-open the issue if you have any ideas.
