### ISSUE TITLE
Support for databinding button attributedTitle or titleLabel.attributedText

### ISSUE THREAD

**Issue by zachgrayio** [gk-brown/MarkupKit#83]
It'd be great if it were possible to do either of the following: 

`<UIButton image="IconFacebook" class="signInButton" style="systemButton" titleLabel.attributedText="$signInWithFacebookAttrText" onPrimaryActionTriggered="..."/>`

or 

`<UIButton image="IconFacebook" class="signInButton" style="systemButton" attributedLabel="$signInWithFacebookAttrText" onPrimaryActionTriggered="..."/>`

Currently, the first seems to do nothing while the second crashes out. I'd love to take a crack at implementing and PRing this myself but I'm rather new to the project and don't know much about it.

**Comment by gk-brown** [comment]
You can't actually set a button's attributed text via the `titleLabel` property - you need to set it like this:

    button.setAttributedTitle(NSAttributedString(string: "Press Me!"), for: .normal)

The same applies to a button's plain text and image. MarkupKit adds `title` and `image` properties to `UIButton` that internally call `setTitle:forState:` and `setImage:forState:` so you can set these values in markup:

    <UIButton title="Hello" image="hello.png"/>

However, I have not added a similar property for attributed text since (to my knowledge) there's no standard way to declaratively represent an attributed string. I've considered supporting RTF or inline HTML, but neither one is ideal. RTF isn't very common, and this would be pretty ugly:

    <UIButton title="&lt;span style='font-weight:bold'&gt;Hello&lt;/span&gt;"/>

In any case, I'm still thinking about it since I do think it would be useful to support declarative attributed text. In the meantime, my suggestion would be to declare an outlet for your button and just set the attributed text programmatically.

**Comment by zachgrayio** [comment]
Makes sense. 

I agree that there's not a great way to handle attributed text, however the ability to databind the attributed text of a label to a variable is nice as it at least removes the need for an iboutlet and allows looser coupling of the code to the view, even if the attributed text string still has to be built programattically. Something like this for buttons would be excellent.

**Comment by gk-brown** [comment]
I could see potentially adding an `attributedTitle` property to `UIButton` that works similarly to how `title` and `image` currently work. You could actually do this in app code as well.

**Comment by gk-brown** [comment]
I just prototyped this and I think it makes sense to add it to the platform. I will probably try to include it in the next release.

**Comment by gk-brown** [comment]
This has been committed to the development branch and will be included in the next release.
