### ISSUE TITLE
RxSwift support

### ISSUE THREAD

**Issue by zachgrayio** [gk-brown/MarkupKit#93]
This might not align to well with your goals for the framework, but I was thinking, it'd be pretty awesome if we could bind to `Observable<String>` properties in markup the same way we can with strings. 

I don't know how feasible this is considering the framework is implemented in obj-c, but figured it's worth chatting about.

**Comment by gk-brown** [comment]
I'd be reluctant to introduce a dependency on another framework in MarkupKit. Could you elaborate a little more on what you are trying to accomplish?

**Comment by gk-brown** [comment]
Still not sure exactly what you are trying to do, but you may be able to accomplish it by overriding `addObserver:forKeyPath:options:context:` and `setValue:forKey:` in your controller. The first method is called to establish the binding from controller to view, and the second is called to notify the controller that the value of a view property has changed.

**Comment by aceontech** [comment]
Yeah, I think @zachgrayio is thinking about some kind of extension which would enable direct data binding to RxSwift observables instead of going through KVO observation of `@dynamic` properties. 

It could make sense to develop this as an external extension, provided the right hooks are available (looks like they might be, from what @gk-brown is saying about `addObserver` and `setValue`). I'm a ReactiveCocoa/ReactiveSwift-user myself, but the concepts lineup pretty well, and there could be value in it, albeit as a separate extension library.

**Comment by gk-brown** [comment]
Makes sense. An extension library would help simplify development of applications that use both frameworks without imposing a hard dependency on one or the other.

**Comment by gk-brown** [comment]
I'm going to close this issue since it seems like any additional effort in this area would most likely take place in an external project.
